### ISSUE TITLE
http://www.steadylearner.com appears to be offline (2023-01-10)

### ISSUE THREAD

**Issue by johnnyutahh** [steadylearner/Rust-Full-Stack#272]
http://www.steadylearner.com appears to be offline (2023-01-10).

Is this project still valid, live, applicable?

To be clear: I'm not trying to be "mean" or act entitled... I super appreciate all the compilation and effort that went into making this project, albeit I'm seeing it for the first time just now. I'm simply asking: is it live and being maintained/applicable (whatever that may mean), either at this github repo or at http://www.steadylearner.com/.

Thanks for any help!

**Comment by steadylearner** [comment]
I am doing other projects but I see some people want this website work again.

The code base that I did use for this project is quite outdated so I will need to rewrite a lot of them to make it online again and it will take some time. But, I will see I can do that later.

Recently, I don't write Rust code much but if you still need help with it, I can help you personally also.

https://t.me/steadylearner

and if you want to find some blogs, you can find it here https://github.com/steadylearner?tab=repositories&q=blog or https://dev.to/steadylearner also.

Hope this helped.

**Comment by steadylearner** [comment]
You should be able to read blogs at https://www.steadylearner.com/blogs page.

I am still working on it so there will be more improvements.
