### ISSUE TITLE
504 Gateway Time-out accesing www.steadylearner.com/blog

### ISSUE THREAD

**Issue by mrsarm** [steadylearner/Rust-Full-Stack#29]
Trying to check your blog I found just that, the site is not working.

**Comment by steadylearner** [comment]
Sorry, I had to repair my laptop and couldn't solve this. If you need to read blog posts, please read them at https://github.com/steadylearner/blog

 I will work on to fix the website to work again and update the website.

**Comment by steadylearner** [comment]
The website is currently back to work. The current server implementation shows some problems. I will update it later.
